import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { validateRecord, addRecord, auditRecords, safeFile, renderRecord } from './records.mjs';

const cli = fileURLToPath(new URL('./curator.mjs', import.meta.url));
const record = () => ({ id:'test-gallery', category:'web', title:'交互作品集', author:'Fixture author', authorUrl:'https://example.org/creator', model:'GPT-6 Astra', modelEvidence:'作者说明正文第二段明确写出模型名。', tools:['HTML','CSS'], sourceUrl:'https://example.org/work/one', sourceType:'作者自述', sourceAccess:'原始来源已读取', secondaryUrl:null, checkedAt:new Date().toISOString().slice(0,10), summary:'一个用于验证内容整理流程的合成案例；不作为真实案例发布。', promptStatus:'未公开', prompt:'', promptSourceUrl:null, reproduction:'未复现', reproductionEvidence:[], limitations:'未进行实际运行验证。', rights:'许可未公开，仅链接引用。' });
const git=(cwd,...args)=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
async function fixture(t){const root=await mkdtemp(path.join(tmpdir(),'gpt6-curator-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'cases/web'),{recursive:true});await writeFile(path.join(root,'cases/web/README.md'),'# Web\n');return root;}

test('record schema accepts complete evidence declarations',()=>assert.deepEqual(validateRecord(record()),[]));
test('rejects unsupported categories, invalid calendar dates and missing rights',()=>{const r=record();r.category='apps';r.checkedAt='2026-02-30';r.rights='';assert.ok(validateRecord(r).length>=3);});
test('secondary sources cannot claim original prompt or first-hand access',()=>{const r=record();r.sourceAccess='仅二手来源';r.secondaryUrl='https://example.org/roundup';r.promptStatus='作者原文';r.prompt='make this';r.promptSourceUrl=r.sourceUrl;assert.ok(validateRecord(r).some(e=>e.includes('二手')));});
test('reproduced claims require evidence, unpublished prompts cannot contain invented text',()=>{const r=record();r.reproduction='已复现';r.prompt='inferred prompt';assert.ok(validateRecord(r).length>=2);});
test('safe prompt fences preserve embedded backticks without creating document headings',()=>{const r=record();r.promptStatus='整理者改写';r.prompt='```\n# embedded\n```';const md=renderRecord(r);assert.match(md,/````text\n```/);});
test('add produces matching record, formatted case and index, and retry is idempotent',async t=>{const root=await fixture(t);const first=await addRecord(root,record());assert.equal(first.status,'created');const second=await addRecord(root,record());assert.equal(second.status,'unchanged');assert.deepEqual(await auditRecords(root),[]);const md=await readFile(path.join(root,'cases/web/test-gallery.md'),'utf8');assert.match(md,/## 权利与署名/);});
test('renaming a case does not bypass canonical URL duplicate detection',async t=>{const root=await fixture(t);await addRecord(root,record());const r=record();r.id='another-title';r.sourceUrl+='/?utm_source=test#view';await assert.rejects(()=>addRecord(root,r),/重复/);});
test('legacy source links participate in duplicate checks',async t=>{const root=await fixture(t);await writeFile(path.join(root,'cases/web/old.md'),'# Old\n[来源](https://example.org/work/one)\n');await assert.rejects(()=>addRecord(root,record()),/重复/);});
test('editing generated markdown or removing an index entry fails audit',async t=>{const root=await fixture(t);await addRecord(root,record());await writeFile(path.join(root,'cases/web/test-gallery.md'),'# forged\n');await writeFile(path.join(root,'cases/web/README.md'),'# Web\n');const errors=await auditRecords(root);assert.ok(errors.some(e=>e.includes('不一致')));assert.ok(errors.some(e=>e.includes('索引')));});
test('rejects traversal and symlink paths',async t=>{const root=await fixture(t);await assert.rejects(()=>safeFile(root,'../escape.md'),/路径/);await symlink(path.dirname(root),path.join(root,'linked'),'junction');await assert.rejects(()=>safeFile(root,'linked/escape.md'),/路径|链接/);});

async function gitFixture(t){const root=await fixture(t);const remote=await mkdtemp(path.join(tmpdir(),'gpt6-remote-'));t.after(()=>rm(remote,{recursive:true,force:true}));git(remote,'init','--bare','--initial-branch=main');git(root,'init','-b','main');git(root,'config','user.name','Fixture');git(root,'config','user.email','fixture@example.org');git(root,'config','core.autocrlf','false');git(root,'config',`url.${remote.replaceAll('\\','/')}.insteadOf`,'https://github.com/zender555/awesome-gpt6.git');git(root,'remote','add','origin','https://github.com/zender555/awesome-gpt6.git');await mkdir(path.join(root,'scripts'));await writeFile(path.join(root,'scripts/check.mjs'),'console.log("fixture check")\n');await writeFile(path.join(root,'.gitignore'),'.local/\n');git(root,'add','.');git(root,'commit','-m','initial');git(root,'push','-u','origin','main');await mkdir(path.join(root,'.local'));return {root,remote};}
function run(root,...args){const r=spawnSync(process.execPath,[cli,...args,'--repo',root],{encoding:'utf8'});return {code:r.status,text:r.stdout+r.stderr};}
async function plan(root){await writeFile(path.join(root,'note.md'),'# Note\n');await writeFile(path.join(root,'.local/files.json'),JSON.stringify(['note.md']));const r=run(root,'plan','--files','.local/files.json','--out','.local/release.json');assert.equal(r.code,0,r.text);return JSON.parse(await readFile(path.join(root,'.local/release.json'),'utf8'));}
test('manifest requires complete case/index/record group',async t=>{const {root}=await gitFixture(t);await addRecord(root,record());await writeFile(path.join(root,'.local/files.json'),JSON.stringify(['cases/web/test-gallery.md']));const r=run(root,'plan','--files','.local/files.json','--out','.local/release.json');assert.equal(r.code,1,r.text);assert.match(r.text,/一起发布/);});
test('manifest detects edited files before publication',async t=>{const {root}=await gitFixture(t);await plan(root);await writeFile(path.join(root,'note.md'),'changed');const r=run(root,'verify-manifest','--manifest','.local/release.json');assert.equal(r.code,1);assert.match(r.text,/指纹/);});
test('unauthorized publication is rejected and unrelated staged files stay untouched',async t=>{const {root,remote}=await gitFixture(t);await plan(root);let r=run(root,'publish','--manifest','.local/release.json');assert.equal(r.code,1);assert.match(r.text,/authorized/);await writeFile(path.join(root,'private-note.md'),'unrelated');git(root,'add','private-note.md');r=run(root,'publish','--manifest','.local/release.json','--authorized');assert.equal(r.code,1);assert.match(r.text,/暂存区/);assert.equal(git(remote,'rev-parse','main'),git(root,'rev-parse','HEAD'));});
test('publish to local fixture remote, verify hashes and retry without duplicate commits',async t=>{const {root,remote}=await gitFixture(t);await plan(root);let r=run(root,'publish','--manifest','.local/release.json','--authorized');assert.equal(r.code,0,r.text);const first=git(remote,'rev-parse','main');r=run(root,'verify-release','--manifest','.local/release.json');assert.equal(r.code,0,r.text);r=run(root,'publish','--manifest','.local/release.json','--authorized');assert.equal(r.code,0,r.text);assert.equal(git(remote,'rev-parse','main'),first);});
test('remote advancement blocks a stale release rather than overwriting it',async t=>{const {root}=await gitFixture(t);await plan(root);await writeFile(path.join(root,'other.md'),'other');git(root,'add','other.md');git(root,'commit','-m','other');git(root,'push');const r=run(root,'publish','--manifest','.local/release.json','--authorized');assert.equal(r.code,1,r.text);assert.match(r.text,/远端已变化/);});
test('a manually added case cannot skip the structured record requirement',async t=>{const {root}=await gitFixture(t);await writeFile(path.join(root,'cases/web/manual.md'),'# Manual\n');await writeFile(path.join(root,'.local/files.json'),JSON.stringify(['cases/web/manual.md']));const r=run(root,'plan','--files','.local/files.json','--out','.local/release.json');assert.equal(r.code,1,r.text);assert.match(r.text,/结构化记录/);});
test('audit rejects stale title and status in category index',async t=>{const root=await fixture(t);await addRecord(root,record());const f=path.join(root,'cases/web/README.md');await writeFile(f,(await readFile(f,'utf8')).replace('交互作品集','过期标题'));assert.ok((await auditRecords(root)).some(e=>e.includes('索引')));});
test('audit detects a duplicate legacy case added after a structured case',async t=>{const root=await fixture(t);await addRecord(root,record());await writeFile(path.join(root,'cases/web/duplicate.md'),'# Duplicate\n[来源](https://example.org/work/one)');assert.ok((await auditRecords(root)).some(e=>e.includes('重复')));});
test('explicit update synchronizes case, record and category metadata',async t=>{const root=await fixture(t);await addRecord(root,record());const updated=record();updated.title='更新后的作品集';await addRecord(root,updated,{update:true});assert.deepEqual(await auditRecords(root),[]);assert.match(await readFile(path.join(root,'cases/web/README.md'),'utf8'),/更新后的作品集/);});
test('externally verified remote SHA can prepare a manifest without transport access',async t=>{const {root,remote}=await gitFixture(t);const base=git(remote,'rev-parse','main');await writeFile(path.join(root,'note.md'),'# Note');await writeFile(path.join(root,'.local/files.json'),'["note.md"]');let r=run(root,'plan','--files','.local/files.json','--out','.local/release.json','--base-commit',base);assert.equal(r.code,1);r=run(root,'plan','--files','.local/files.json','--out','.local/release.json','--base-commit',base,'--remote-verified');assert.equal(r.code,0,r.text);});
